root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/lunarleague serve"
  cmd = "go build -o ./tmp/lunarleague ./cmd/server"
  delay = 500
  exclude_dir = ["tmp", "bin", "db/migrations"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tmpl", "tpl", "html", "yaml"]
  kill_delay = "2s"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
